name: Build And Deploy

on:
  push:
    branches: ['master']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install & Build
        run: |
          npm install yarn
          yarn install
          yarn build

      - name: Copy to development
        env:
          SRC_FOLDER_PATH: 'build'
          TARGET_BRANCH: 'development'
        run: |
          files=$(find $SRC_FOLDER_PATH -type f)
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git fetch                         
          git checkout $TARGET_BRANCH
          git checkout ${GITHUB_REF##*/} -- $files
          git add -A
          git diff-index --quiet HEAD ||  git commit -am "chore: copy build files to development"
          git push origin $TARGET_BRANCH

      # - name: Upload Build Artifact
      #   uses: actions/upload-artifact@v3.1.0
      #   with:
      #     name: build-artifact
      #     path: |
      #       build
      #       ecosystem.config.js
      #       nest-cli.json
      #       package.json
      #     retention-days: 1

  # deploy:
  #   needs:
  #     - build
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Download Artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: build-artifact

  # - name: SCP to EC2 Server
  #   uses: appleboy/scp-action@v0.1.3
  #   with:
  #     host: ${{ secrets.SSH_HOST }}
  #     username: ${{ secrets.SSH_USERNAME }}
  #     key: ${{ secrets.SSH_KEY }}
  #     port: ${{ secrets.SSH_PORT }}
  #     source: 'dist, ecosystem.config.js, nest-cli.json, package.json'
  #     target: '/home/${{ secrets.SSH_USERNAME }}/baolocre_apis_dev'

  # - name: SSH to EC2 Server
  #   uses: appleboy/ssh-action@master
  #   with:
  #     host: ${{ secrets.SSH_HOST }}
  #     username: ${{ secrets.SSH_USERNAME }}
  #     key: ${{ secrets.SSH_KEY }}
  #     port: ${{ secrets.SSH_PORT }}
  #     script_stop: true
  #     script: |
  #       cd baolocre_apis_dev
  #       yarn install
  #       pm2 start ecosystem.config.js
